// Dart SDK 3.0.1
// Flutter SDK 3.10.1
// course_guide 2.0.0+1
// ├── back_button_interceptor 6.0.2
// │   ├── collection...
// │   └── flutter...
// ├── badges 3.1.1
// │   └── flutter...
// ├── cached_network_image 3.2.3
// │   ├── cached_network_image_platform_interface 2.0.0
// │   │   ├── flutter...
// │   │   └── flutter_cache_manager...
// │   ├── cached_network_image_web 1.0.2
// │   │   ├── cached_network_image_platform_interface...
// │   │   ├── flutter...
// │   │   └── flutter_cache_manager...
// │   ├── flutter...
// │   ├── flutter_cache_manager 3.3.0
// │   │   ├── clock...
// │   │   ├── collection...
// │   │   ├── file...
// │   │   ├── flutter...
// │   │   ├── http...
// │   │   ├── path...
// │   │   ├── path_provider...
// │   │   ├── pedantic 1.11.1
// │   │   ├── rxdart 0.27.7
// │   │   ├── sqflite 2.2.8+4
// │   │   │   ├── flutter...
// │   │   │   ├── path...
// │   │   │   └── sqflite_common 2.4.5
// │   │   │       ├── meta...
// │   │   │       ├── path...
// │   │   │       └── synchronized 3.1.0
// │   │   └── uuid 3.0.7
// │   │       └── crypto...
// │   └── octo_image 1.0.2
// │       ├── flutter...
// │       └── flutter_blurhash 0.7.0
// │           └── flutter...
// ├── cloud_firestore 4.8.0
// │   ├── cloud_firestore_platform_interface 5.15.0
// │   │   ├── _flutterfire_internals 1.3.2
// │   │   │   ├── collection...
// │   │   │   ├── firebase_core...
// │   │   │   ├── firebase_core_platform_interface...
// │   │   │   ├── flutter...
// │   │   │   └── meta...
// │   │   ├── collection...
// │   │   ├── firebase_core...
// │   │   ├── flutter...
// │   │   ├── meta...
// │   │   └── plugin_platform_interface...
// │   ├── cloud_firestore_web 3.6.0
// │   │   ├── _flutterfire_internals...
// │   │   ├── cloud_firestore_platform_interface...
// │   │   ├── collection...
// │   │   ├── firebase_core...
// │   │   ├── firebase_core_web...
// │   │   ├── flutter...
// │   │   ├── flutter_web_plugins...
// │   │   └── js...
// │   ├── collection...
// │   ├── firebase_core...
// │   ├── firebase_core_platform_interface...
// │   ├── flutter...
// │   └── meta...
// ├── cupertino_icons 1.0.5
// ├── emailjs 1.1.0
// │   ├── flutter...
// │   └── http...
// ├── firebase_auth 4.6.2
// │   ├── firebase_auth_platform_interface 6.15.2
// │   │   ├── _flutterfire_internals...
// │   │   ├── collection...
// │   │   ├── firebase_core...
// │   │   ├── flutter...
// │   │   ├── meta...
// │   │   └── plugin_platform_interface...
// │   ├── firebase_auth_web 5.5.2
// │   │   ├── firebase_auth_platform_interface...
// │   │   ├── firebase_core...
// │   │   ├── firebase_core_web...
// │   │   ├── flutter...
// │   │   ├── flutter_web_plugins...
// │   │   ├── http_parser...
// │   │   ├── js...
// │   │   └── meta...
// │   ├── firebase_core...
// │   ├── firebase_core_platform_interface...
// │   ├── flutter...
// │   └── meta...
// ├── firebase_core 2.13.1
// │   ├── firebase_core_platform_interface 4.8.0
// │   │   ├── collection...
// │   │   ├── flutter...
// │   │   ├── flutter_test...
// │   │   ├── meta...
// │   │   └── plugin_platform_interface 2.1.4
// │   │       └── meta...
// │   ├── firebase_core_web 2.5.0
// │   │   ├── firebase_core_platform_interface...
// │   │   ├── flutter...
// │   │   ├── flutter_web_plugins...
// │   │   ├── js...
// │   │   └── meta...
// │   ├── flutter...
// │   └── meta...
// ├── firebase_storage 11.2.2
// │   ├── firebase_core...
// │   ├── firebase_core_platform_interface...
// │   ├── firebase_storage_platform_interface 4.4.2
// │   │   ├── collection...
// │   │   ├── firebase_core...
// │   │   ├── flutter...
// │   │   ├── meta...
// │   │   └── plugin_platform_interface...
// │   ├── firebase_storage_web 3.6.2
// │   │   ├── _flutterfire_internals...
// │   │   ├── async...
// │   │   ├── firebase_core...
// │   │   ├── firebase_core_web...
// │   │   ├── firebase_storage_platform_interface...
// │   │   ├── flutter...
// │   │   ├── flutter_web_plugins...
// │   │   ├── http...
// │   │   ├── js...
// │   │   └── meta...
// │   └── flutter...
// ├── flutter 0.0.0
// │   ├── characters 1.3.0
// │   ├── collection 1.17.1
// │   ├── js 0.6.7
// │   │   └── meta...
// │   ├── material_color_utilities 0.2.0
// │   ├── meta 1.9.1
// │   ├── sky_engine 0.0.99
// │   └── vector_math 2.1.4
// ├── flutter_launcher_icons 0.13.1
// │   ├── args 2.4.1
// │   ├── checked_yaml 2.0.3
// │   │   ├── json_annotation...
// │   │   ├── source_span...
// │   │   └── yaml...
// │   ├── cli_util 0.4.0
// │   │   ├── meta...
// │   │   └── path...
// │   ├── image 4.0.17
// │   │   ├── archive 3.3.7
// │   │   │   ├── crypto...
// │   │   │   ├── path...
// │   │   │   └── pointycastle 3.7.3
// │   │   │       ├── collection...
// │   │   │       ├── convert 3.1.1
// │   │   │       │   └── typed_data...
// │   │   │       └── js...
// │   │   ├── meta...
// │   │   └── xml 6.3.0
// │   │       ├── collection...
// │   │       ├── meta...
// │   │       └── petitparser 5.4.0
// │   │           └── meta...
// │   ├── json_annotation 4.8.1
// │   │   └── meta...
// │   ├── path...
// │   └── yaml 3.1.2
// │       ├── collection...
// │       ├── source_span...
// │       └── string_scanner...
// ├── flutter_neat_and_clean_calendar 0.3.13+28
// │   ├── flutter...
// │   ├── intl 0.18.1
// │   │   ├── clock...
// │   │   ├── meta...
// │   │   └── path...
// │   └── macos_ui 1.12.2
// │       └── flutter...
// ├── flutter_screenutil 5.8.3
// │   └── flutter...
// ├── flutter_staggered_grid_view 0.6.2
// │   └── flutter...
// ├── flutter_test 0.0.0
// │   ├── async 2.11.0
// │   │   ├── collection...
// │   │   └── meta...
// │   ├── boolean_selector 2.1.1
// │   │   ├── source_span...
// │   │   └── string_scanner...
// │   ├── characters...
// │   ├── clock 1.1.1
// │   ├── collection...
// │   ├── fake_async 1.3.1
// │   │   ├── clock...
// │   │   └── collection...
// │   ├── flutter...
// │   ├── js...
// │   ├── matcher 0.12.15
// │   │   ├── async...
// │   │   ├── meta...
// │   │   ├── stack_trace...
// │   │   ├── term_glyph...
// │   │   └── test_api...
// │   ├── material_color_utilities...
// │   ├── meta...
// │   ├── path 1.8.3
// │   ├── source_span 1.9.1
// │   │   ├── collection...
// │   │   ├── path...
// │   │   └── term_glyph...
// │   ├── stack_trace 1.11.0
// │   │   └── path...
// │   ├── stream_channel 2.1.1
// │   │   └── async...
// │   ├── string_scanner 1.2.0
// │   │   └── source_span...
// │   ├── term_glyph 1.2.1
// │   ├── test_api 0.5.1
// │   │   ├── async...
// │   │   ├── boolean_selector...
// │   │   ├── collection...
// │   │   ├── matcher...
// │   │   ├── meta...
// │   │   ├── source_span...
// │   │   ├── stack_trace...
// │   │   ├── stream_channel...
// │   │   ├── string_scanner...
// │   │   └── term_glyph...
// │   └── vector_math...
// ├── font_awesome_flutter 10.4.0
// │   └── flutter...
// ├── glassmorphism 3.0.0
// │   └── flutter...
// ├── go_router 7.1.1
// │   ├── collection...
// │   ├── flutter...
// │   ├── flutter_web_plugins...
// │   ├── logging 1.2.0
// │   └── meta...
// ├── google_fonts 4.0.4
// │   ├── crypto 3.0.3
// │   │   └── typed_data 1.3.2
// │   │       └── collection...
// │   ├── flutter...
// │   ├── http 0.13.6
// │   │   ├── async...
// │   │   ├── http_parser 4.0.2
// │   │   │   ├── collection...
// │   │   │   ├── source_span...
// │   │   │   ├── string_scanner...
// │   │   │   └── typed_data...
// │   │   └── meta...
// │   └── path_provider 2.0.15
// │       ├── flutter...
// │       ├── path_provider_android 2.0.27
// │       │   ├── flutter...
// │       │   └── path_provider_platform_interface...
// │       ├── path_provider_foundation 2.2.3
// │       │   ├── flutter...
// │       │   └── path_provider_platform_interface...
// │       ├── path_provider_linux 2.1.11
// │       │   ├── ffi 2.0.2
// │       │   ├── flutter...
// │       │   ├── path...
// │       │   ├── path_provider_platform_interface...
// │       │   └── xdg_directories 1.0.0
// │       │       ├── meta...
// │       │       ├── path...
// │       │       └── process 4.2.4
// │       │           ├── file...
// │       │           ├── path...
// │       │           └── platform...
// │       ├── path_provider_platform_interface 2.0.6
// │       │   ├── flutter...
// │       │   ├── platform 3.1.0
// │       │   └── plugin_platform_interface...
// │       └── path_provider_windows 2.1.6
// │           ├── ffi...
// │           ├── flutter...
// │           ├── path...
// │           ├── path_provider_platform_interface...
// │           └── win32 4.1.4
// │               └── ffi...
// ├── hexcolor 3.0.1
// │   ├── flutter...
// │   └── flutter_web_plugins 0.0.0
// │       ├── characters...
// │       ├── collection...
// │       ├── flutter...
// │       ├── js...
// │       ├── material_color_utilities...
// │       ├── meta...
// │       └── vector_math...
// ├── image_picker 0.8.7+5
// │   ├── flutter...
// │   ├── image_picker_android 0.8.6+17
// │   │   ├── flutter...
// │   │   ├── flutter_plugin_android_lifecycle 2.0.15
// │   │   │   └── flutter...
// │   │   └── image_picker_platform_interface...
// │   ├── image_picker_for_web 2.1.12
// │   │   ├── flutter...
// │   │   ├── flutter_web_plugins...
// │   │   └── image_picker_platform_interface...
// │   ├── image_picker_ios 0.8.7+4
// │   │   ├── flutter...
// │   │   └── image_picker_platform_interface...
// │   └── image_picker_platform_interface 2.6.3
// │       ├── cross_file 0.3.3+4
// │       │   ├── js...
// │       │   └── meta...
// │       ├── flutter...
// │       ├── http...
// │       └── plugin_platform_interface...
// ├── provider 6.0.5
// │   ├── collection...
// │   ├── flutter...
// │   └── nested 1.0.0
// │       └── flutter...
// ├── shared_preferences 2.1.1
// │   ├── flutter...
// │   ├── shared_preferences_android 2.1.4
// │   │   ├── flutter...
// │   │   └── shared_preferences_platform_interface...
// │   ├── shared_preferences_foundation 2.2.2
// │   │   ├── flutter...
// │   │   └── shared_preferences_platform_interface...
// │   ├── shared_preferences_linux 2.2.0
// │   │   ├── file 6.1.4
// │   │   │   ├── meta...
// │   │   │   └── path...
// │   │   ├── flutter...
// │   │   ├── path...
// │   │   ├── path_provider_linux...
// │   │   ├── path_provider_platform_interface...
// │   │   └── shared_preferences_platform_interface...
// │   ├── shared_preferences_platform_interface 2.2.0
// │   │   ├── flutter...
// │   │   └── plugin_platform_interface...
// │   ├── shared_preferences_web 2.1.0
// │   │   ├── flutter...
// │   │   ├── flutter_web_plugins...
// │   │   └── shared_preferences_platform_interface...
// │   └── shared_preferences_windows 2.2.0
// │       ├── file...
// │       ├── flutter...
// │       ├── path...
// │       ├── path_provider_platform_interface...
// │       ├── path_provider_windows...
// │       └── shared_preferences_platform_interface...
// ├── timeago 3.4.0
// │   └── intl...
// ├── url_launcher 6.1.11
// │   ├── flutter...
// │   ├── url_launcher_android 6.0.35
// │   │   ├── flutter...
// │   │   └── url_launcher_platform_interface...
// │   ├── url_launcher_ios 6.1.4
// │   │   ├── flutter...
// │   │   └── url_launcher_platform_interface...
// │   ├── url_launcher_linux 3.0.5
// │   │   ├── flutter...
// │   │   └── url_launcher_platform_interface...
// │   ├── url_launcher_macos 3.0.5
// │   │   ├── flutter...
// │   │   └── url_launcher_platform_interface...
// │   ├── url_launcher_platform_interface 2.1.2
// │   │   ├── flutter...
// │   │   └── plugin_platform_interface...
// │   ├── url_launcher_web 2.0.17
// │   │   ├── flutter...
// │   │   ├── flutter_web_plugins...
// │   │   └── url_launcher_platform_interface...
// │   └── url_launcher_windows 3.0.6
// │       ├── flutter...
// │       └── url_launcher_platform_interface...
// ├── url_strategy 0.2.0
// │   └── flutter_web_plugins...
// └── video_player 2.6.1
//     ├── flutter...
//     ├── html 0.15.3
//     │   ├── csslib 0.17.3
//     │   │   └── source_span...
//     │   └── source_span...
//     ├── video_player_android 2.4.8
//     │   ├── flutter...
//     │   └── video_player_platform_interface...
//     ├── video_player_avfoundation 2.4.6
//     │   ├── flutter...
//     │   └── video_player_platform_interface...
//     ├── video_player_platform_interface 6.1.0
//     │   ├── flutter...
//     │   └── plugin_platform_interface...
//     └── video_player_web 2.0.16
//         ├── flutter...
//         ├── flutter_web_plugins...
//         └── video_player_platform_interface...
