// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4dfYSEQ_6X50utQsaBInQuX6jq-ur5tU',
    appId: '1:758883292655:android:8240604e9733a14a80921a',
    messagingSenderId: '758883292655',
    projectId: 'course-guide-2022',
    storageBucket: 'course-guide-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr_YQAW-lzRuqRmL4TIR7frZjfcIf6KvI',
    appId: '1:758883292655:ios:9175651dff0dd97780921a',
    messagingSenderId: '758883292655',
    projectId: 'course-guide-2022',
    storageBucket: 'course-guide-2022.appspot.com',
    iosClientId: '758883292655-v67b9af683kjpnkudkijmrg6f4ms9upv.apps.googleusercontent.com',
    iosBundleId: 'com.lemasystems.courseGuide',
  );
}
