Map<String, List<String>> personalityTypesAndCareers = {
  'ISTJ': [
    'Accountant',
    'Financial Analyst',
    'Project Manager',
    'Civil Engineer',
    'Military Officer',
  ],
  'ISFJ': [
    'Teacher',
    'Nurse',
    'Librarian',
    'Social Worker',
    'Administrative Assistant',
  ],
  'INFJ': [
    'Counselor',
    'Psychologist',
    'Writer',
    'Humanitarian',
    'Graphic Designer',
  ],
  'INTJ': [
    'Scientist',
    'Architect',
    'Computer Programmer',
    'Entrepreneur',
    'Attorney',
  ],
  'ISTP': [
    'Detective',
    'Pilot',
    'Engineer',
    'Forensic Scientist',
    'Surgeon',
  ],
  'ISFP': [
    'Artist',
    'Musician',
    'Chef',
    'Photographer',
    'Veterinarian',
  ],
  'INFP': [
    'Writer',
    'Counselor',
    'Social Worker',
    'Teacher',
    'Psychologist',
  ],
  'INTP': [
    'Scientist',
    'Architect',
    'Computer Programmer',
    'Researcher',
    'Engineer',
  ],
  'ESTP': [
    'Salesperson',
    'Entrepreneur',
    'Paramedic',
    'Athlete',
    'Detective',
  ],
  'ESFP': [
    'Actor/Actress',
    'Event Planner',
    'Interior Designer',
    'Flight Attendant',
    'Physical Therapist',
  ],
  'ENFP': [
    'Public Relations Specialist',
    'Writer',
    'Teacher',
    'Counselor',
    'Marketing Manager',
  ],
  'ENTP': [
    'Lawyer',
    'Entrepreneur',
    'Marketing Strategist',
    'Politician',
    'Management Consultant',
  ],
  'ESTJ': [
    'Manager',
    'Police Officer',
    'Financial Officer',
    'Military Officer',
    'Sales Manager',
  ],
  'ESFJ': [
    'Nurse',
    'Event Planner',
    'Teacher',
    'Human Resources Manager',
    'Customer Service Representative',
  ],
  'ENFJ': [
    'Teacher',
    'Counselor',
    'Social Worker',
    'Human Resources Manager',
    'Public Relations Manager',
  ],
  'ENTJ': [
    'CEO/Executive',
    'Lawyer',
    'Entrepreneur',
    'Management Consultant',
    'Financial Analyst',
  ],
};
